### ISSUE TITLE
Matching up Options probabilities to strike prices

### ISSUE THREAD

**Issue by brettabroad** [rickyars/options-pricing#1]
Hoping this is the right place to comment!

Re: my email comment: 

We will need to compare our probabilities with the market's. For GREK, that means knowing what the market is implying with strikes at $8.00, $9.00, $10.00 and $11.00.

**Comment by rickyars** [comment]
I updated the app so you can enter your own strike price. It now also displays the option chain after generating the first BSM cone.

**Comment by brettabroad** [comment]
I've been using the NASDAQ site lately for option chains. Can your program pull in info from there too?

For example for GREK: http://www.nasdaq.com/symbol/grek/option-chain?money=all&dateindex=2

Just so I'm sure I understand what I'm looking at, what is the cone saying about probabilities for a call of $11.00 and a put of $8.00 for Sept. 15th, 2017?

**Comment by rickyars** [comment]
Looks like my only options using quantmod are Yahoo and Google. I can try to write something custom to pull from NASDAQ, but I really had webscraping. It's a pain to do and websites change so often the solutions usually break after a few weeks.

Is there a reason that Yahoo or Google isn't working for you?

**Comment by brettabroad** [comment]
I asked because of a comment that Miller made. He mentioned that unless the numbers came from a brokerage site or NASDAQ, they weren't as reliable.
